// Copied verbatim from karamatch-web/src/design/icons.tsx — the icon set is
// geometry, not markup, so the name union carries over unchanged.
export type IconName =
    | "pin"
    | "mic"
    | "spark"
    | "users"
    | "calendar"
    | "bell"
    | "star"
    | "check"
    | "close"
    | "chevronLeft"
    | "chevronRight"
    | "chevronDown"
    | "search"
    | "plus"
    | "minus"
    | "camera"
    | "send"
    | "sun"
    | "moon"
    | "logout"
    | "crown"
    | "music"
    | "locate"
    | "pencil"
    | "clock"
    | "card"
    | "userPlus"
    | "trash"
    | "heart"
    | "info"
    | "share"
    | "sliders";
