// `storybook.requires` is generated by the `withStorybook` Metro plugin
// (see metro.config.js) from this directory's `main.ts` stories glob —
// don't hand-edit it, and don't commit it; it's gitignored.
import AsyncStorage from "@react-native-async-storage/async-storage";
import { view } from "./storybook.requires";

const StorybookUI = view.getStorybookUI({
    storage: {
        getItem: AsyncStorage.getItem,
        setItem: AsyncStorage.setItem,
    },
});

export default StorybookUI;
